server:
  port: 7984

spring:
  application:
    name: cloud-pm
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://192.168.1.248:3306/uxzhao?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: U4c&sQT4